version: "3"
services:
  broker:
    image: 'eclipse-mosquitto'
    ports:
      - '1883:1883'
  database:
    image: 'mongo'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=admin'
      - 'MONGO_INITDB_ROOT_PASSWORD=CHANGEME'
    ## Uncomment the ports section below to grant direct access to MongoDB
    ## Before 2014 this was the common way to upload data to NightScout
    ## In Summer 2014 it was deprecated in favor of the new REST API
    # ports:
    #  - '27017:27017'

  nightscout:
    build:
      context: https://github.com/nightscout/cgm-remote-monitor.git
      dockerfile: Dockerfile
    environment:
      - 'API_SECRET=CHANGEME_PLEASE'
      - 'MONGO_CONNECTION=mongodb://admin:CHANGEME@database/admin'
      - 'MQTT_MONITOR=mqtt://CHANGEME@broker'
      - 'PORT=1337'
    depends_on:
      - broker
      - database
    ports:
      - '1337:1337'
