##### NOTE ####### 
# This docker compose file requires docker compose 1.5 to be installed
# before calling docker-compose, ensure you've ready the Readme file first

broker:
  image: 'prologic/mosquitto:latest'
  ports:
    - '1883:1883'
database:
  image: 'tutum/mongodb:latest'
  environment:
    - MONGODB_PASS:${MONGODB_PASS}

# Uncomment if you want to expose the MongoDB port directly
# If you're using the API interface (highly recommended) then you can 
# safely leave this commented out 
#  ports:
#    - '27017:27017'

nightscout:
  image: 'nightscout/cgm-remote-monitor-development:latest'
  environment:
    - API_SECRET:${NIGHTSCOUT_APIKEY}
    - 'MONGO_CONNECTION=mongodb://admin:${MONGODB_PASS}@database/admin'
    - 'MQTT_MONITOR=mqtt://${MQTT_USER}@broker'
    - PORT:1337
  links:
    - broker
    - database
  ports:
    - '1337:1337'
